apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataphpapache
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 200Mi
  hostPath:
    path: /data/php-app
