apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  labels:
    app: php-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      volumes:
        - name: phpapache-persistent-storage
          persistentVolumeClaim:
            claimName: data-phpapacheclaim
      containers:
      - name: php-app
        image: "dockerprivatereg.azurecr.io/dockerstack_php_apache:B170"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: phpapache-persistent-storage
          mountPath: /DocumentRoot
      imagePullSecrets:
        - name: secret
