version: '3'

services:

  #PHP and Apache
  php-apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: ckerprivatereg.azurecr.io/dockerstack_php_apache:B${BUILD_NUMBER}
    restart: always
    ports:
        - "8083:80"
    volumes:
        - "./DocumentRoot/:/var/www/html/"
    depends_on:
        - db
  #db
  db:   
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: ckerprivatereg.azurecr.io/dockerstack_db:B${BUILD_NUMBER}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: db123
    volumes:
        - ./dbdata:/var/lib/mysql
    ports:
        - "8002:3306"
   

