version: '3'

services:

  #PHP and Apache
  php-apache:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
        - "${HTTP_PORT}:80"
    volumes:
        - "./DocumentRoot/:/var/www/html/"
    depends_on:
        - db
  #db
  db:   
    build:
      context: .
      dockerfile: mysql.Dockerfile
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
        - ./dbdata:/var/lib/mysql
    ports:
        - "8002:3306"
   

