version: '3'

services:

  #PHP and Apache
  php-apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: registry.gitlab.com/registry12/dockerstack_php_apache:B${BUILD_NUMBER}
    restart: always
    ports:
        - "8083:80"
    volumes:
        - "./DocumentRoot/:/var/www/html/"
    depends_on:
        - db
  #db
  db:   
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: registry.gitlab.com/registry12/dockerstack_db:B${BUILD_NUMBER}
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "dockerlamp"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "dockerlamp"
    volumes:
        - ./dbdata:/var/lib/mysql
    ports:
        - "8002:3306"
   

