version: '3'

services:

  #PHP and Apache
  php-apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: dockerpvregistry.azurecr.io/dockerstack_php_apache
    restart: always
    ports:
        - "8083:80"
    volumes:
        - "./DocumentRoot/:/var/www/html/"
    depends_on:
        - db
  #db
  db:   
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: dockerpvregistry.azurecr.io/dockerstack_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "dockerlamp"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "dockerlamp"
    volumes:
        - ./dbdata:/var/lib/mysql
    ports:
        - "8002:3306"
   

